version: "3"
services:
  ner_service:
    container_name: "ner"
    build:
      context: ${USERS_SERVICE_BASE_PATH}/web
      dockerfile: Dockerfile
    ports:
     - "${USERS_SERVICE_PORT}:5000"
    command: "python3 app.py"
    restart: "on-failure"
    volumes:
      - "./web:/code"

  ner_storage:
    image: redis
    ports:
      - "${USERS_SERVICE_REDIS_PORT}:6379"
